### PR TITLE
Load spells from spells.json instead of Python file

### PR DESCRIPTION
**Pull request by lordp**
I've created a simple Windows based editor for your spelldeck (https://github.com/lordp/dnd-spellcard-editor) and I've made use of JSON to store the spell details.

This pull request is to change generate.py to load the JSON file instead of using the Python file (spells.py).

### CODE REVIEW

**Comment by StephenSwat** [comment]
Hi @lordp,

Good idea to move the spells to a JSON file and I like the work you've done on the spell editor. Some worries about this pull request though:

- Can you properly indent the JSON file? Makes it a lot more readable. `json.dumps` supports an `indent

**Comment by stephenswat** [comment]
Hi @lordp,

Good idea to move the spells to a JSON file and I like the work you've done on the spell editor. Some worries about this pull request though:
- Can you properly indent the JSON file? Makes it a lot more readable. `json.dumps` supports an `indent` parameter which does this I believe
- What is the type of the component list in this system? It was a set in the old Python file and this might be useful later.

Thanks for the work you've done so far, keep it going!

**Comment by lordp** [comment]
Hi @StephenSwat 

The classes and components in the JSON file convert to a list in Python, which I believe very similar to a set. I haven't done much with Python 2.7 (the editor is written/compiled using 3.4), so I may be wrong about that.

**Comment by stephenswat** [comment]
Thanks for updating that, `spells.json` looks good now. About the set thing: I find the spells to output by using the intersection of two sets (if you are not aware, the intersection of two sets is a new set containing all the elements that are in both sets) and checking the length of that set. For example, _Alter Self_ would have a set containing _Sorcerer_ and _Wizard_ and if we were then to request all spells for the Wizard and Rogue classes, Alter Self would be included as the intersection of `{Sorcerer, Wizard}` and `{Wizard, Rogue}` is `{Wizard}` which is non-empty.

I don't think this works with lists but I could be wrong. Could you look into this? Then I would be glad to merge your commit.

**Comment by lordp** [comment]
I've done some searching and found http://www.saltycrane.com/blog/2008/01/how-to-find-intersection-and-union-of/ from 8 years ago (!) that still works. I've always felt casting was a bit iffy, but it's pretty clean.

**Pull request merged**
